Template creation
josueetcom/TeachMe pull request #6
Opened 2021-04-03 04:31 UTC by ObiTracks

Just pushed the templates to this branch template-creation. Personally I think formatting the code can wait for later since its not too bad imo right now.

2021-04-03 08:03 UTC, josueetcom requested changes
Most of the comments I left were stylistic ones but there are a few structural ones. The stylistic ones don't necessarily be addressed 100% (especially if it becomes to tedious) but do take a look.

Otherwise the pages look pretty good though I'm a little surprised they're all in the `templates/` folder instead of next to the `index.html` file. I would've expected only HTML templates/snippets to be in a subfolder

2021-04-03 08:03 UTC, josueetcom commented on src/main/webapp/css/main.css
> +  margin: 0 10px;
[Alphabetize declarations.](https://google.github.io/styleguide/htmlcssguide.html#Declaration_Order)

Here and everywhere else in this CSS file as well as the SCSS file.

You might try pasting your CSS in a tool that does this for you. E.g. in [this tool](http://www.lonniebest.com/FormatCSS/) if you change this setting and then click **Format CSS**.
![image](https://user-images.githubusercontent.com/8023233/113471345-97142700-9410-11eb-83fc-f0b2b1fe9d09.png)
A slight caveat is that it'll remove the lines between your rules, but maybe that's easier to add back in.

Or if that's too tricky both Cloud Shell Editor and VS Code have an action for sorting lines you select..

2021-04-03 08:03 UTC, josueetcom commented on src/main/webapp/css/style.css.map
> +    "mappings": "AAAA,AAAA,CAAC,CAAA;EACG,UAAU,EAAE,UAAU;EACtB,WAAW,EAAE,uBAAuB;CACvC;;AAED,AAAA,IAAI,CAAA;EACA,MAAM,EAAE,CAAC;EACT,OAAO,EAAE,CAAC;CACb;;AAED,AAAA,KAAK,CAAA;EACD,OAAO,EAAE,IAAI;EACb,q
What does this do?

2021-04-03 08:03 UTC, josueetcom commented on src/main/webapp/css/components.css
> +  border-radius: 20px;
[Alphabetize declarations.](https://google.github.io/styleguide/htmlcssguide.html#Declaration_Order)

2021-04-03 08:03 UTC, josueetcom commented on src/main/webapp/css/main.css
> +a:hover {
[Separate rules by new lines.](https://google.github.io/styleguide/htmlcssguide.html#Rule_Separation)

2021-04-03 08:03 UTC, josueetcom commented on src/main/webapp/css/main.css
> +#profile-username {
[Separate rules by new lines.](https://google.github.io/styleguide/htmlcssguide.html#Rule_Separation)

2021-04-03 08:03 UTC, josueetcom commented on src/main/webapp/css/main.css
> +.menu-tab > a {
[Separate rules by new lines.](https://google.github.io/styleguide/htmlcssguide.html#Rule_Separation)

2021-04-03 08:03 UTC, josueetcom commented on src/main/webapp/css/main.css
> +.menu-tab:hover {
[Separate rules by new lines.](https://google.github.io/styleguide/htmlcssguide.html#Rule_Separation)

2021-04-03 08:03 UTC, josueetcom commented on src/main/webapp/css/main.css
> +button.menu-button {
[Separate rules by new lines.](https://google.github.io/styleguide/htmlcssguide.html#Rule_Separation)

2021-04-03 08:03 UTC, josueetcom commented on src/main/webapp/css/style.scss
> +#content-profile {
[Separate rules by new lines.](https://google.github.io/styleguide/htmlcssguide.html#Rule_Separation)

2021-04-03 08:03 UTC, josueetcom commented on src/main/webapp/css/style.scss
> +.profile-grid {
[Separate rules by new lines.](https://google.github.io/styleguide/htmlcssguide.html#Rule_Separation)

2021-04-03 08:03 UTC, josueetcom commented on src/main/webapp/css/style.scss
> +.img-extrasmall {
[Separate rules by new lines.](https://google.github.io/styleguide/htmlcssguide.html#Rule_Separation)

2021-04-03 08:03 UTC, josueetcom commented on src/main/webapp/css/style.scss
> +.img-small {
[Separate rules by new lines.](https://google.github.io/styleguide/htmlcssguide.html#Rule_Separation)

2021-04-03 08:03 UTC, josueetcom commented on src/main/webapp/css/style.scss
> +.img-med {
[Separate rules by new lines.](https://google.github.io/styleguide/htmlcssguide.html#Rule_Separation)

2021-04-03 08:03 UTC, josueetcom commented on src/main/webapp/css/style.scss
> +.img-large {
[Separate rules by new lines.](https://google.github.io/styleguide/htmlcssguide.html#Rule_Separation)

2021-04-03 08:03 UTC, josueetcom commented on src/main/webapp/templates/dashboard.html
> +        <a href="./dashboard.html" id="user-profile">All Users</a>
[Use valid HTML where possible.](https://google.github.io/styleguide/htmlcssguide.html#HTML_Validity)

The tool linked from there is catching multiple elements with the ID `user-profile`, which is not valid as `id` should be a unique identifier. Use `class` instead if you're trying to style things similarly.

2021-04-03 08:03 UTC, josueetcom commented on src/main/webapp/templates/matchdashboard.html
> +        <a href="" id="user-profile">All Users</a>
[Use valid HTML where possible.](https://google.github.io/styleguide/htmlcssguide.html#HTML_Validity)

The tool linked from there is catching multiple elements with the ID `user-profile` along with some other errors.

2021-04-03 08:03 UTC, josueetcom commented on src/main/webapp/templates/matchdashboard.html
> +          <button action="" id="match-button">Match</button>
`button`s don't have the `action` attribute.

2021-04-03 08:03 UTC, josueetcom commented on src/main/webapp/templates/menucode.html
> +    <a href="" id="user-profile">All Users</a>
You've got duplicate elements with the `user-profile` ID in this file as well.

2021-04-03 08:03 UTC, josueetcom commented on src/main/webapp/templates/userprofile-update.html
> +        <a href="" id="user-profile">All Users</a>
[Use valid HTML where possible.](https://google.github.io/styleguide/htmlcssguide.html#HTML_Validity)

The tool linked from there is catching multiple elements with the ID `user-profile` along with some other errors.

2021-04-03 08:03 UTC, josueetcom commented on src/main/webapp/templates/userprofile.html
> +        <a href="" id="user-profile">All Users</a>
[Use valid HTML where possible.](https://google.github.io/styleguide/htmlcssguide.html#HTML_Validity)

The tool linked from there is catching multiple elements with the ID `user-profile` along with some other errors.

2021-04-03 08:03 UTC, josueetcom commented on src/main/webapp/css/style.css
> +  -ms-flex-direction: column;
Helps to check these CSS files with a [CSS validator](https://jigsaw.w3.org/css-validator/validator). Some of these prefixed properties are browser specific for very older browsers and may no longer be necessary.

2021-04-03 08:03 UTC, josueetcom commented on src/main/webapp/templates/menucode.html
> +<div class="menu">
Is looks like this file's code is duplicated in the other files? Wasn't this meant to be [`fetch`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/template)-ed and then inserted into a [`<template>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/template) element (or something of the sort) to deduplicate this code?

2021-04-03 08:03 UTC, josueetcom commented on src/main/webapp/templates/dashboard.html
> +        <img class="img-small" src="/assets/svgs/account.svg" alt="" />
[Provide alternative contents for multimedia.](https://google.github.io/styleguide/htmlcssguide.html#Multimedia_Fallback) Here and elsewhere `alt` is not set or is empty.  `alt` should be a description of the media that goes there.

2021-04-03 08:03 UTC, josueetcom commented on src/main/webapp/css/main.css
> +  font-size: 14px;
[Use shorthand properties where possible.](https://google.github.io/styleguide/htmlcssguide.html#Shorthand_Properties) Here and elsewhere.

This might be a bit annoying to do everywhere so maybe just only in places where it makes sense (e.g. multiple `font`/`padding`/`margin` properties).

2021-04-03 08:04 UTC, josueetcom commented
One more note for future reference: It _really_ helps reviewers if you break these PRs down so that they can be more focused. E.g. you could do the main page and the main styling files in one PR. In a dependent PR could be other pages and their styling files (if they one), etc.

2021-04-03 18:16 UTC, ObiTracks commented on src/main/webapp/css/style.css.map
> +    "mappings": "AAAA,AAAA,CAAC,CAAA;EACG,UAAU,EAAE,UAAU;EACtB,WAAW,EAAE,uBAAuB;CACvC;;AAED,AAAA,IAAI,CAAA;EACA,MAAM,EAAE,CAAC;EACT,OAAO,EAAE,CAAC;CACb;;AAED,AAAA,KAAK,CAAA;EACD,OAAO,EAAE,IAAI;EACb,q
This is autogenerated by the scss compiler I use on vscode, its not necessary for production just for scss-css conversion

2021-04-03 18:24 UTC, ObiTracks commented on src/main/webapp/templates/userprofile.html
> +        <a href="" id="user-profile">All Users</a>
Simple copying mistake slipped my eye

2021-04-03 18:25 UTC, ObiTracks commented on src/main/webapp/css/style.css
> +  -ms-flex-direction: column;
These are auto generated by the scss compiler I mentioned

2021-04-03 18:31 UTC, ObiTracks commented on src/main/webapp/templates/menucode.html
> +<div class="menu">
I left that file there in case I'm able to make the menu work as a template

2021-04-03 18:32 UTC, ObiTracks commented on src/main/webapp/templates/menucode.html
> +<div class="menu">
I'll delete for now

2021-04-03 18:33 UTC, ObiTracks commented
> One more note for future reference: It _really_ helps reviewers if you break these PRs down so that they can be more focused. E.g. you could do the main page and the main styling files in one PR. In a dependent PR could be other pages and their styling files (if they one), etc.

Yeah my top priority after redesigning was to get it all up asap, will definitely do in the future sure

2021-04-03 18:35 UTC, ObiTracks commented
A lot of the problems you noticed were actually from obsolete css files I stopped using and forgot to delete. In the next commit, those files will be gone and you'll find the other stylistic changes adressed for the most part (except for alphabetizing attributes).

2021-04-03 18:59 UTC, ObiTracks reviewed
Fixed most of the things you mentioned except alphabetizing for now

2021-04-04 05:46 UTC, josueetcom approved these changes
Just two minor nits otherwise to ensure the HTML is valid otherwise it looks good to me 👍

2021-04-04 05:46 UTC, josueetcom commented on src/main/webapp/matchdashboard.html
> +          <button action="" id="match-button">Match</button>
`button`s still don't have `action` attributes...

2021-04-04 05:46 UTC, josueetcom commented on src/main/webapp/matchdashboard.html
> +        <a href="" id="user-profile">Username</a>
You still have duplicate `user-profile` IDs in this file and in some of the others. That's one of the downsides of having duplicate HTML code in multiple files, you have to remember to update all of them. Maybe a follow-up PR can refactor this common `menu` div so contributors don't have to remember to update all of them when making menu changes.

2021-04-04 18:59 UTC, JoseGrangerSalgado approved these changes
LGTM

2021-04-04 19:02 UTC, jpaints3 approved these changes

2021-04-04 23:06 UTC, merged